# Generated by Django 2.1 on 2020-05-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='consultant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.Doctor'),
        ),
    ]
